import Head from "next/head";

import { ApolloClient, InMemoryCache, gql } from "@apollo/client";

import Layout from "@components/Layout";
import Container from "@components/Container";
import Button from "@components/Button";

import styles from "@styles/Page.module.scss";

export default function Category({ category }) {
  const products = category.products;

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <h1>{category.name}</h1>

        <h2>Products</h2>

        <ul className={styles.products}>
          {products.map((product) => {
            return (
              <li key={product.slug}>
                <a href={`/products/${product.slug}`}>
                  <div className={styles.productImage}>
                    <img
                      width={product.image.width}
                      height={product.image.height}
                      src={product.image.url}
                      alt={product.slug}
                    />
                  </div>
                  <h3 className={styles.productTitle}>{product.name}</h3>
                  <p className={styles.productPrice}>
                    ${product.price.toFixed(2)}
                  </p>
                </a>
                <p>
                  <Button
                    className="snipcart-add-item"
                    data-item-id={product.id}
                    data-item-name={product.name}
                    data-item-price={product.price}
                    data-item-image={product.image.url}
                    data-item-url={`/products/${product.slug}`}
                  >
                    Add to Cart
                  </Button>
                </p>
              </li>
            );
          })}
        </ul>
      </Container>
    </Layout>
  );
}

export async function getStaticProps({ params }) {
  const client = new ApolloClient({
    uri:
      "https://api-sa-east-1.hygraph.com/v2/cl66jhys4awc201t52k7463ow/master",
    cache: new InMemoryCache(),
  });

  const data = await client.query({
    query: gql`
      query PageCategory($slug: String) {
        category(where: { slug: $slug }) {
          id
          name
          slug
          products {
            ... on Product {
              id
              name
              price
              slug
              image
            }
          }
        }
      }
    `,
    variables: {
      slug: params.categorySlug,
    },
  });

  const category = data.data.category;

  return {
    props: {
      category,
    },
  };
}

export async function getStaticPaths() {
  const client = new ApolloClient({
    uri:
      "https://api-sa-east-1.hygraph.com/v2/cl66jhys4awc201t52k7463ow/master",
    cache: new InMemoryCache(),
  });

  const data = await client.query({
    query: gql`
      query PageCategories {
        categories {
          id
          name
          slug
          products {
            ... on Product {
              id
              name
              price
              slug
              image
            }
          }
        }
      }
    `,
  });

  const paths = data.data.categories.map((category) => {
    return {
      params: {
        categorySlug: category.slug,
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
}
